[project]
name = "fast-mae-split"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "pytest>=8.4.1",
    "scikit-learn>=1.7.1",
]
